# Generated by Django 5.1.4 on 2026-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="analysis_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="analysis",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysis",
            name="diagnosis",
            field=models.CharField(default="Incertain", max_length=20),
        ),
        migrations.AddField(
            model_name="analysis",
            name="doctor_diagnosis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="doctor_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="doctor_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="radios/"),
        ),
    ]
